import csv
import sys

# List of building process related variables
buildingprocess_related = [
    "CMAKE_ADSP_ROOT", "CMAKE_AIX_SHARED_LIBRARY_ARCHIVE", "CMAKE_AIX_EXPORT_ALL_SYMBOLS",
    "CMAKE_ANDROID_ANT_ADDITIONAL_OPTIONS", "CMAKE_ANDROID_API", "CMAKE_ANDROID_API_MIN",
    "CMAKE_ANDROID_ARCH", "CMAKE_ANDROID_ARCH_ABI", "CMAKE_ANDROID_ARM_MODE", "CMAKE_ANDROID_ARM_NEON",
    "CMAKE_ANDROID_ASSETS_DIRECTORIES", "CMAKE_ANDROID_EXCEPTIONS", "CMAKE_ANDROID_GUI", "CMAKE_ANDROID_JAR_DEPENDENCIES",
    "CMAKE_ANDROID_JAR_DIRECTORIES", "CMAKE_ANDROID_JAVA_SOURCE_DIR", "CMAKE_ANDROID_NATIVE_LIB_DEPENDENCIES",
    "CMAKE_ANDROID_NATIVE_LIB_DIRECTORIES", "CMAKE_ANDROID_NDK", "CMAKE_ANDROID_NDK_DEPRECATED_HEADERS",
    "CMAKE_ANDROID_NDK_TOOLCHAIN_HOST_TAG", "CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION", "CMAKE_ANDROID_PROCESS_MAX",
    "CMAKE_ANDROID_PROGUARD", "CMAKE_ANDROID_PROGUARD_CONFIG_PATH", "CMAKE_ANDROID_RTTI", "CMAKE_ANDROID_SECURE_PROPS_PATH",
    "CMAKE_ANDROID_SKIP_ANT_STEP", "CMAKE_ANDROID_STANDALONE_TOOLCHAIN", "CMAKE_ANDROID_STL_TYPE", "CMAKE_APPLE_SILICON_PROCESSOR",
    "CMAKE_ARCHIVE_OUTPUT_DIRECTORY", "CMAKE_ARCHIVE_OUTPUT_DIRECTORY_<CONFIG>", "CMAKE_AUTOGEN_BETTER_GRAPH_MULTI_CONFIG",
    "CMAKE_AUTOGEN_COMMAND_LINE_LENGTH_MAX", "CMAKE_AUTOGEN_ORIGIN_DEPENDS", "CMAKE_AUTOGEN_PARALLEL",
    "CMAKE_AUTOGEN_USE_SYSTEM_INCLUDE", "CMAKE_AUTOGEN_VERBOSE", "CMAKE_AUTOMOC", "CMAKE_AUTOMOC_COMPILER_PREDEFINES",
    "CMAKE_AUTOMOC_DEPEND_FILTERS", "CMAKE_AUTOMOC_MACRO_NAMES", "CMAKE_AUTOMOC_MOC_OPTIONS", "CMAKE_AUTOMOC_PATH_PREFIX",
    "CMAKE_AUTOMOC_EXECUTABLE", "CMAKE_AUTORCC", "CMAKE_AUTORCC_OPTIONS", "CMAKE_AUTORCC_EXECUTABLE", "CMAKE_AUTOUIC",
    "CMAKE_AUTOUIC_OPTIONS", "CMAKE_AUTOUIC_SEARCH_PATHS", "CMAKE_AUTOUIC_EXECUTABLE", "CMAKE_BUILD_RPATH",
    "CMAKE_BUILD_RPATH_USE_ORIGIN", "CMAKE_BUILD_WITH_INSTALL_NAME_DIR", "CMAKE_BUILD_WITH_INSTALL_RPATH", "CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY",
    "CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY_<CONFIG>", "CMAKE_COMPILE_WARNING_AS_ERROR", "CMAKE_<CONFIG>_POSTFIX", "CMAKE_CROSS_CONFIGS",
    "CMAKE_CTEST_ARGUMENTS", "CMAKE_CUDA_RESOLVE_DEVICE_SYMBOLS", "CMAKE_CUDA_RUNTIME_LIBRARY", "CMAKE_CUDA_SEPARABLE_COMPILATION",
    "CMAKE_CXX_MODULE_STD", "CMAKE_CXX_SCAN_FOR_MODULES", "CMAKE_DEBUG_POSTFIX", "CMAKE_DEFAULT_BUILD_TYPE", "CMAKE_DEFAULT_CONFIGS",
    "CMAKE_DEPENDS_USE_COMPILER", "CMAKE_DISABLE_PRECOMPILE_HEADERS", "CMAKE_DLL_NAME_WITH_SOVERSION", "CMAKE_ENABLE_EXPORTS",
    "CMAKE_EXECUTABLE_ENABLE_EXPORTS", "CMAKE_EXE_LINKER_FLAGS", "CMAKE_EXE_LINKER_FLAGS_<CONFIG>", "CMAKE_EXE_LINKER_FLAGS_<CONFIG>_INIT",
    "CMAKE_EXE_LINKER_FLAGS_INIT", "CMAKE_EXPORT_FIND_PACKAGE_NAME", "CMAKE_FOLDER", "CMAKE_Fortran_FORMAT", "CMAKE_Fortran_MODULE_DIRECTORY",
    "CMAKE_Fortran_PREPROCESS", "CMAKE_FRAMEWORK", "CMAKE_FRAMEWORK_MULTI_CONFIG_POSTFIX_<CONFIG>", "CMAKE_GHS_NO_SOURCE_GROUP_FILE",
    "CMAKE_GLOBAL_AUTOGEN_TARGET", "CMAKE_GLOBAL_AUTOGEN_TARGET_NAME", "CMAKE_GLOBAL_AUTORCC_TARGET", "CMAKE_GLOBAL_AUTORCC_TARGET_NAME",
    "CMAKE_GNUtoMS", "CMAKE_INCLUDE_CURRENT_DIR", "CMAKE_INCLUDE_CURRENT_DIR_IN_INTERFACE", "CMAKE_INSTALL_NAME_DIR", "CMAKE_INSTALL_REMOVE_ENVIRONMENT_RPATH",
    "CMAKE_INSTALL_RPATH", "CMAKE_INSTALL_RPATH_USE_LINK_PATH", "CMAKE_INTERPROCEDURAL_OPTIMIZATION", "CMAKE_INTERPROCEDURAL_OPTIMIZATION_<CONFIG>",
    "CMAKE_<LANG>_CLANG_TIDY", "CMAKE_<LANG>_CLANG_TIDY_EXPORT_FIXES_DIR", "CMAKE_<LANG>_COMPILER_LAUNCHER", "CMAKE_<LANG>_CPPCHECK",
    "CMAKE_<LANG>_CPPLINT", "CMAKE_<LANG>_INCLUDE_WHAT_YOU_USE", "CMAKE_<LANG>_LINK_GROUP_USING_<FEATURE>", "CMAKE_<LANG>_LINK_GROUP_USING_<FEATURE>_SUPPORTED",
    "CMAKE_<LANG>_LINK_LIBRARY_<FEATURE>_ATTRIBUTES", "CMAKE_<LANG>_LINK_LIBRARY_FILE_FLAG", "CMAKE_<LANG>_LINK_LIBRARY_FLAG", "CMAKE_<LANG>_LINK_LIBRARY_USING_<FEATURE>",
    "CMAKE_<LANG>_LINK_LIBRARY_USING_<FEATURE>_SUPPORTED", "CMAKE_<LANG>_LINK_WHAT_YOU_USE_FLAG", "CMAKE_<LANG>_LINKER_LAUNCHER", "CMAKE_<LANG>_USING_LINKER_MODE",
    "CMAKE_<LANG>_USING_LINKER_<TYPE>", "CMAKE_<LANG>_VISIBILITY_PRESET", "CMAKE_LIBRARY_OUTPUT_DIRECTORY", "CMAKE_LIBRARY_OUTPUT_DIRECTORY_<CONFIG>",
    "CMAKE_LIBRARY_PATH_FLAG", "CMAKE_LINK_DEF_FILE_FLAG", "CMAKE_LINK_DEPENDS_NO_SHARED", "CMAKE_LINK_DEPENDS_USE_LINKER",
    "CMAKE_LINK_GROUP_USING_<FEATURE>", "CMAKE_LINK_GROUP_USING_<FEATURE>_SUPPORTED", "CMAKE_LINK_INTERFACE_LIBRARIES", "CMAKE_LINK_LIBRARIES_STRATEGY",
    "CMAKE_LINK_LIBRARY_<FEATURE>_ATTRIBUTES", "CMAKE_LINK_LIBRARY_FILE_FLAG", "CMAKE_LINK_LIBRARY_FLAG", "CMAKE_LINK_LIBRARY_USING_<FEATURE>",
    "CMAKE_LINK_LIBRARY_USING_<FEATURE>_SUPPORTED", "CMAKE_LINK_WHAT_YOU_USE", "CMAKE_LINK_WHAT_YOU_USE_CHECK", "CMAKE_LINKER_TYPE", "CMAKE_MACOSX_BUNDLE",
    "CMAKE_MACOSX_RPATH", "CMAKE_MAP_IMPORTED_CONFIG_<CONFIG>", "CMAKE_MODULE_LINKER_FLAGS", "CMAKE_MODULE_LINKER_FLAGS_<CONFIG>",
    "CMAKE_MODULE_LINKER_FLAGS_<CONFIG>_INIT", "CMAKE_MODULE_LINKER_FLAGS_INIT", "CMAKE_MSVC_DEBUG_INFORMATION_FORMAT", "CMAKE_MSVC_RUNTIME_LIBRARY",
    "CMAKE_MSVCIDE_RUN_PATH", "CMAKE_NINJA_OUTPUT_PATH_PREFIX", "CMAKE_NO_BUILTIN_CHRPATH", "CMAKE_NO_SYSTEM_FROM_IMPORTED",
    "CMAKE_OPTIMIZE_DEPENDENCIES", "CMAKE_OSX_ARCHITECTURES", "CMAKE_OSX_DEPLOYMENT_TARGET", "CMAKE_OSX_SYSROOT", "CMAKE_PCH_INSTANTIATE_TEMPLATES",
    "CMAKE_PCH_WARN_INVALID", "CMAKE_PDB_OUTPUT_DIRECTORY", "CMAKE_PDB_OUTPUT_DIRECTORY_<CONFIG>", "CMAKE_PLATFORM_NO_VERSIONED_SONAME",
    "CMAKE_POSITION_INDEPENDENT_CODE", "CMAKE_RUNTIME_OUTPUT_DIRECTORY", "CMAKE_RUNTIME_OUTPUT_DIRECTORY_<CONFIG>", "CMAKE_SHARED_LIBRARY_ENABLE_EXPORTS",
    "CMAKE_SHARED_LINKER_FLAGS", "CMAKE_SHARED_LINKER_FLAGS_<CONFIG>", "CMAKE_SHARED_LINKER_FLAGS_<CONFIG>_INIT", "CMAKE_SHARED_LINKER_FLAGS_INIT",
    "CMAKE_SKIP_BUILD_RPATH", "CMAKE_SKIP_INSTALL_RPATH", "CMAKE_STATIC_LINKER_FLAGS", "CMAKE_STATIC_LINKER_FLAGS_<CONFIG>",
    "CMAKE_STATIC_LINKER_FLAGS_<CONFIG>_INIT", "CMAKE_STATIC_LINKER_FLAGS_INIT", "CMAKE_TASKING_TOOLSET", "CMAKE_TRY_COMPILE_CONFIGURATION",
    "CMAKE_TRY_COMPILE_NO_PLATFORM_VARIABLES", "CMAKE_TRY_COMPILE_PLATFORM_VARIABLES", "CMAKE_TRY_COMPILE_TARGET_TYPE", "CMAKE_UNITY_BUILD",
    "CMAKE_UNITY_BUILD_BATCH_SIZE", "CMAKE_UNITY_BUILD_UNIQUE_ID", "CMAKE_VERIFY_INTERFACE_HEADER_SETS", "CMAKE_VISIBILITY_INLINES_HIDDEN",
    "CMAKE_VS_DEBUGGER_COMMAND", "CMAKE_VS_DEBUGGER_COMMAND_ARGUMENTS", "CMAKE_VS_DEBUGGER_ENVIRONMENT", "CMAKE_VS_DEBUGGER_WORKING_DIRECTORY",
    "CMAKE_VS_GLOBALS", "CMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD", "CMAKE_VS_INCLUDE_PACKAGE_TO_DEFAULT_BUILD", "CMAKE_VS_JUST_MY_CODE_DEBUGGING",
    "CMAKE_VS_NO_COMPILE_BATCHING", "CMAKE_VS_SDK_EXCLUDE_DIRECTORIES", "CMAKE_VS_SDK_EXECUTABLE_DIRECTORIES", "CMAKE_VS_SDK_INCLUDE_DIRECTORIES",
    "CMAKE_VS_SDK_LIBRARY_DIRECTORIES", "CMAKE_VS_SDK_LIBRARY_WINRT_DIRECTORIES", "CMAKE_VS_SDK_REFERENCE_DIRECTORIES", "CMAKE_VS_SDK_SOURCE_DIRECTORIES",
    "CMAKE_VS_WINRT_BY_DEFAULT", "CMAKE_WATCOM_RUNTIME_LIBRARY", "CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS", "CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS_<CONFIG>",
    "CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS_NO_CHECK", "CMAKE_WINDOWS_PATH_MAX_LENGTH", "CMAKE_WINDOWS_UDK_PATH", "CMAKE_WIN32_EXECUTABLE",
    "CMAKE_WIN32_EXE_LINKER_FLAGS", "CMAKE_WIN32_LINKER_FLAGS", "CMAKE_WINDOWS_BUILTIN_DLL_PATH", "CMAKE_WINDOWS_CRT_DEBUGGING",
    "CMAKE_WINDOWS_SYSTEM_INCLUDE_PATH", "CMAKE_WINDOWS_UCRT_INCLUDE_PATH", "CMAKE_WINDOWS_UCRT_LIBRARY_PATH", "CMAKE_WINDOWS_X64_LIBRARY_DIRS"
]


# Function to check if any building process-related variable is present in the reachability string
def contains_building_process_related_variable(reachability_str):
    return any(var in reachability_str for var in buildingprocess_related)

# Read the target CSV file specified in the command line argument
def process_csv(file_name):
    total_deps = 0  # Total number of dependencies
    building_process_related_deps = 0  # Number of dependencies containing building process-related variables
    reachability_non_empty = 0  # Number of rows where 'reachability' column is not empty

    # Open and read the CSV file
    with open(file_name, mode='r', encoding='utf-8') as file:
        reader = csv.reader(file)
        
        # Skip the header row if any
        next(reader, None)
        
        # Iterate through each row in the CSV
        for row in reader:
            num = row[0].strip()  # The first column is 'num'
            reachability = row[2].strip() if len(row) > 2 else ""  # The 'reachability' column
            
            if num:  # Only process rows where 'num' is not empty
                total_deps += 1
                if reachability:
                    reachability_non_empty += 1
                    if contains_building_process_related_variable(reachability):
                        building_process_related_deps += 1

    # Calculate the percentage of dependencies containing building process-related variables
    building_process_related_percentage = (building_process_related_deps / total_deps * 100) if total_deps > 0 else 0
    # Calculate the percentage of dependencies with building process-related variables among non-empty reachability rows
    building_process_related_percentage_non_empty = (building_process_related_deps / reachability_non_empty * 100) if reachability_non_empty > 0 else 0

    # Output the results
    print(f"Total dependencies: {total_deps}")
    print(f"Dependencies with building process-related variables: {building_process_related_deps}")
    print(f"Percentage of total deps: {building_process_related_percentage:.2f}%")
    print(f"Percentage of deps with reachability not empty: {building_process_related_percentage_non_empty:.2f}%")

# Main function to execute the script
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <csv_file>")
        sys.exit(1)

    # Process the specified CSV file
    process_csv(sys.argv[1])
